blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/devkimchi/battle-school-lunch-workshop/blob/main/SUPPORT.md
    about: Review support options before opening an issue.
